services:
  php:
    build:
      dockerfile: ./.infrastructure/docker/php/Dockerfile
      target: build-dev
      context: .
      args:
        - COMPOSER_HOME=/var/www/html/.composer
    env_file: .env
    environment:
      COMPOSER_HOME: /var/www/html/.composer